### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by nativanando** [phosphor-icons/phosphor-react#12]
Hi, I've been using phosphor-react in some projects and I identified some bundle size problems.. Analysing the bundle I could realize that phosport-react is using almost 60% of the space used.

I don't know it's the expected behavior so I opened this issue to report this situation!

![bundle-size-phosport](https://user-images.githubusercontent.com/13206713/119356660-1093fd00-bc7d-11eb-9515-ba29e51a8bf0.png)

**Comment by rektdeckard** [comment]
The react library fully supports tree-shaking, so it likely comes down to your bundler configuration or the way you're importing the icons. In apps bootstrapped with `create-react-app`, or when using most modern bundlers, simply using destructuring imports should work fine:

```ts
import { Smiley, Rainbow } from "phosphor-react";
```
![Screenshot from 2021-05-24 23-28-51](https://user-images.githubusercontent.com/26732044/119435819-f4c64080-bce8-11eb-9e58-e99a6764fea6.png)


Using the default import, `import Phosphor from "phosphor-react";` or importing everything `import * as Icons from "phosphor-react";` may or may not import the entire contents of the library, so try not to do that.

![Screenshot from 2021-05-24 23-28-27](https://user-images.githubusercontent.com/26732044/119435829-fabc2180-bce8-11eb-849a-6cd02cf2248c.png)


If you need to, you can import icons directly from the bundled source:

```tsx
import Smiley from "phosphor-react/dist/icons/Smiley.esm.js";
```

**Comment by nativanando** [comment]
Thanks for the explanation, I was using destructuring imports and the bundle it was still big.. But, Happily the problem was in the lib version I was using (1.0.0) I've just update to 1.2.1 and the problem solved! :D

**Comment by dnsking** [comment]
This is still happening in [1.4.1]

**Comment by Adam-Collier** [comment]
Same here using 1.4.0!

**Comment by JoTrdl** [comment]
I confirm, still happening in `1.4.1`

**Comment by lmichailian** [comment]
Some news on this ?

**Comment by rektdeckard** [comment]
@lmichailian can you provide details on your environment, bundler, and usage? As stated before, the current version of this package is tree-shakeable, but that does not mean your bundler can do it.
