### ISSUE TITLE
CHANGELOGS

### ISSUE THREAD

**Issue by tmilewski** [phosphor-icons/phosphor-react#16]
Please implement a CHANGELOG. There are breaking changes happening (export renaming) on minor versions and having to go through commits to figure out why, or if it'll affect someone, is less-than-ideal.

Thank you.

**Comment by rektdeckard** [comment]
This is 1000% valid, apologies for any inconvenience. We maintain a changelog at [phosphor-home](https://github.com/phosphor-icons/phosphor-home/releases) which calls this out, but we clearly broke semver in this case.

In future, we'll post releases with changelogs across all implementations, and follow versioning conventions more closely.

**Comment by tmilewski** [comment]
@rektdeckard No problem. This is awesome, thank you!
