### ISSUE TITLE
Title or alt text for svg icons

### ISSUE THREAD

**Issue by im-me** [phosphor-icons/phosphor-react#22]
It is not possible to add title or alt text like in img tags to these icons. E.g. for screen-readers.

**Comment by rektdeckard** [comment]
It is possible by adding a child `<title>` tag (and `<desc>`, if you want) to the icon,l. This is the spec-compliant way of making SVGs accessible.

**Comment by rektdeckard** [comment]
Though your PR does seem like a fair convenience feature to include. Please make the requested changes and I'll merge!

**Comment by im-me** [comment]
Thanks. I just made the changes :)
