### ISSUE TITLE
AnimateTransform transform (rotation) does not work in Safari

### ISSUE THREAD

**Issue by TerencedzLi** [phosphor-icons/phosphor-react#25]
Have a look at this [section of the docs](https://github.com/phosphor-icons/phosphor-react#composability) in Chrome where the purple box is rotating.

On Safari, only the opacity animation is working.

**Comment by rektdeckard** [comment]
Hi Terrence. It's just an example of how you can modify an icon by passing children to it -- we don't make guarantees for what browser supports what features. Admittedly, SVG SMIL animation has poor support and we might want to use a different example.

If you're looking to animate icons, just use CSS.
