### ISSUE TITLE
Add `aria-label` in addition to the `alt` prop

### ISSUE THREAD

**Issue by brandonleboeuf** [phosphor-icons/phosphor-react#30]
Browsers usually display the `<title>` as a tool tip, but for a11y, shouldn't this also have the ~aria-labelledby~ aria-label?

MDN refrence: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title

**Comment by rektdeckard** [comment]
That's a good shout-out. We'll add this to the upcoming 2.0 release. Thanks @brandonleboeuf!

**Comment by rektdeckard** [comment]
Wait, it looks like this attribute is for use when the element is labeled by visible text, which is not the case with icons. Are you sure there is an accessibility concern? I am pretty sure the `<title>` element achieves the desired effect for screen readers.

**Comment by brandonleboeuf** [comment]
Good catch @rektdeckard ! I meant `aria-label`, not `aria-labelledby`.

It is needed, as the icons are currently being skipped by the screen reader, even when there is something passed via the phosphor alt prop. As a work around, I have been adding a wrapper div with the aria-label around any phosphor icon that needs to be read by the screen reader. 

From MDN on the title not being read by screen readers: "Text in a <title> element is not rendered as part of the graphic, but browsers usually display it as a tooltip. If an element can be described by visible text, it is recommended to reference that text with an [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) attribute rather than using the <title> element."

Though, looking at aria-labelledby, it does [state to use `aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby#:~:text=If%20there%20is%20no%20content%20that%20can%20be%20referenced%20to%20create%20an%20accessible%20name%2C%20the%20aria%2Dlabel%20attribute%20should%20be%20used%20instead.) instead if there is no visible text to reference, as you pointed out.

**Comment by rektdeckard** [comment]
Noted! Though, as our library docs mention, any and valid SVG attributes you add to an icon will be applied to the rendered DOM node, so the real solution for you to just add that attribute Our `title` fix was specifically to address `<svg>` elements not respecting this attribute in the same way that HTML elements do, IE will not show a native tooltip on hover.

```tsx
<House size={32} aria-label="An icon of a house" />
```

This will do you right. [Working example](https://codesandbox.io/p/sandbox/withered-wood-begnxz?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A14%7D%5D).

**Comment by brandonleboeuf** [comment]
Thank you!

I think having the [`alt` prop](https://github.com/phosphor-icons/phosphor-react#:~:text=alt%3F%3A%20string%20%E2%80%93%20Add%20accessible%20alt%20text%20to%20an%20icon.) makes it feel like an <img> element vs an <svg> element, which would also make me think that the alt text would be the needed fix vs adding the `aria-label`?

It would be nice to have **aria-label?** added to Props section of the readme.md so that it eliminates that confusion since the docs currently state that the alt prop will "add accessible alt text to an icon".

**Comment by rektdeckard** [comment]
This is good by me 👍

**Comment by benface** [comment]
I am a bit confused by the resolution here. What is the point of the `alt` prop if it's not to provide an accessible label to screen readers? 🤔 I feel pretty strongly that it should set `aria-label` on the `<svg>`, not a `<title>` (which _is_ accessible in some browsers but not all, e.g. Safari based on my tests). Would you please reconsider @brandonleboeuf? 🙏 Happy to submit a PR.

**Comment by benface** [comment]
I am a bit confused by the resolution here. What is the point of the `alt` prop if it's not to provide an accessible label to screen readers? 🤔 I feel pretty strongly that it should set `aria-label` on the `<svg>`, not a `<title>` (which _is_ accessible in some browsers but not all, e.g. Safari based on my tests). Would you please reconsider @rektdeckard? 🙏 Happy to submit a PR.

**Comment by rektdeckard** [comment]
@benface honestly, I don't think we should have done the alt thing to begin with. I took the suggestion in #22 and the changes made in #23 to mean that this *would* be accessible to screen readers. And though I don't like to add needless shorthands for things that have a perfectly good idiomatic/native way to do it, I merged it anyway. It seems this was not a good assumption.

The issues I see with modifying it further to add an `aria-label` attribute is that:
1. You can already just add an `aria-label` to the icon as a regular prop, and this is what I'm arguing should be done
2. What happens if you have both an `alt` and `aria-label` prop? Which takes precedence? (discussed similar thing in #83)

Shorthands for things that are already short are bad. The thing I'd consider doing is deprecating the `alt` prop altogether, and recommending using the native HTML approach.

**Comment by benface** [comment]
Ah, I understand @rektdeckard. Good idea to deprecate it then. (I would personally like if `aria-label` was required for icons, but I understand that's an unpopular opinion.)

**Comment by rektdeckard** [comment]
@benface I'll remove it from the `IconProps` type in the next minor version, but will probably keep the behavior around, just to safely deprecate.

Would like to educate myself a bit more on the accessibility best practices here, but it seems like there are definitely some cases where icons do not need to be labeled, such as when used for decorative purposes or made redundant by control/input/button labels. Not sure if I would want to force it.

**Comment by benface** [comment]
Yes @rektdeckard you are definitely right, but I prefer making it required so the developer is forced to think about it. And, if there is no need for a label, they can do `alt=""`, [like for `img`](https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/alternative-text/#:~:text=An%20empty%20string%20stored%20in,readers%20to%20skip%20this%20image.).
